resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: yurtcluster-operator-manager
  newName: registry.cn-hangzhou.aliyuncs.com/ecp_builder/yurtcluster-operator-manager
  newTag: v1.0.2
