resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: yurtcluster-operator-manager
  newName: openyurt/yurtcluster-operator-manager
  newTag: v0.6.1
