# Default values for yurtcluster-operator chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

manager:
  replicas: 1
  image: "openyurt/yurtcluster-operator-manager:v0.6.1"
  imagePullPolicy: Always

agent:
  image: "openyurt/yurtcluster-operator-agent:v0.6.1"
  imagePullPolicy: Always
  transHealthCheckTimeout : 5m


## sub-charts configuration
# values for yurt-controller-manager subchart
yurt-controller-manager:
  manager:
    replicas: 3
    image: "openyurt/yurt-controller-manager:v0.6.0"
    imagePullPolicy: IfNotPresent
    nodeSelector:
      openyurt.io/is-edge-worker: "false"
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
    tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule

# values for yurt-app-manager subchart
yurt-app-manager:
  manager:
    replicas: 3
    image: "openyurt/yurt-app-manager:v0.5.0"
    imagePullPolicy: IfNotPresent
    nodeSelector:
      openyurt.io/is-edge-worker: "false"
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
    tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
